module.exports = {
    CHANNEL_CREATE: 'CHANNEL_CREATE',
    CHANNEL_CREATE_ECHO: 'CHANNEL_CREATE_ECHO',

    GET_ALL_CHANNELS: 'GET_ALL_CHANNELS',
    GET_ALL_CHANNELS_ANSWER: 'GET_ALL_CHANNELS_ANSWER',

    GET_ALL_MESSAGES_FROM_CHANNEL: 'GET_ALL_MESSAGES_FROM_CHANNEL',
    GET_ALL_MESSAGES_FROM_CHANNEL_ANSWER: 'GET_ALL_MESSAGES_FROM_CHANNEL_ANSWER',

    POST_MESSAGE: 'POST_MESSAGE',
    POST_MESSAGE_ECHO: 'POST_MESSAGE_ECHO',

    USER_CONNECT_TO_CHANNEL: 'USER_CONNECT_TO_CHANNEL',
    USER_CONNECT_TO_CHANNEL_ECHO: 'USER_CONNECT_TO_CHANNEL_ECHO',
    USER_DISCONNECT_FROM_CHANNEL: 'USER_DISCONNECT_FROM_CHANNEL',
    USER_DISCONNECT_FROM_CHANNEL_ECHO: 'USER_DISCONNECT_FROM_CHANNEL_ECHO',

    USER_SET_NEW_NAME: 'USER_SET_NEW_NAME',
    USER_SET_NEW_NAME_ANSWER: 'USER_SET_NEW_NAME_ANSWER',

    USERS_ONLINE_ANSWER: 'USERS_ONLINE_ANSWER',
    USER_ONLINE_ECHO: 'USER_ONLINE_ECHO',
    USER_OFFLINE_ECHO: 'USER_OFFLINE_ECHO',
};